### ISSUE TITLE
Need to refresh fragments for some values to update

### ISSUE THREAD

**Issue by Afra-r** [CMPUT301W23T11/QRHunterApp-T11#78]
This should be fixed by adding a loading icon of some sort and then automatically refreshing the fragment

**Comment by apollo-online** [comment]
Specifically, QR code does appear on profile page without refreshing after being added and after being deleted.

**Comment by apollo-online** [comment]
> Specifically, QR code does appear on profile page without refreshing after being added and after being deleted.

Fixed.
